name: Deploy React App to GitHub Pages

#Simple comment

# Trigger on pushes to main or manually
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write     # allow reading the repo
  pages: write        # allow writing to Pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          # cache: 'npm'

      - name: Install dependencies
        run: npm install

      

      - name: Build for production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages         # The branch to deploy to (GitHub Pages default)
          folder: dist             # The folder (built site) to deploy